# Generated by Django 3.2.9 on 2022-02-13 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('mail', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('half', models.BooleanField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('place', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('work', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('mentee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentee', to='home.participant')),
                ('mentor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='home.participant')),
            ],
        ),
    ]
